export enum InspectionType{
  SPECIAL = 'SPECIAL',
  RENEWABLE = 'RENEWABLE',
  PERIODICAL = 'PERIODICAL',
  INTERMEDIATE = 'INTERMEDIATE',
  ANNUAL = 'ANNUAL',
  INITIAL = 'INITIAL',
  INTERIM = 'INTERIM',
  ENTRY = 'ENTRY',
  BETWEEN_TWO_DD = 'BETWEEN_TWO_DD',
  COMPLETE = 'COMPLETE'
}
